title: "Jekyll-Theme-MDUI"
description: "A Jekyll theme based on MDUI"
url: "https://20-1-skku-oss.github.io/2020-1-OSS-9/"
baseurl: 
remote theme: kejunmao/jekyll-theme-mdui
author: "KeJun"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
